### PR TITLE
ToBeOfUse PR

### PR DESCRIPTION
**Pull request by cseitz**
@toBeOfUse we'll continue here from #23

### CODE REVIEW

**Comment by cseitz** [comment]
I made some changes to the get involved section, particularly making both the discord and mailing list seem more uniform when both are present. @toBeOfUse 

Take a look, let me know what you think.

**Comment by toBeOfUse** [comment]
I'm going to be honest: I'm kind of ["you ain't gonna need it"](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) when it comes to things like the ability to bring back the email signup form, which may never need to be done; I usually delete old code that I don't need in a project, secure in the knowledge that it'll be available in the git history as long as the project lives. [(Every file ever deleted from a repository can be displayed with a single git command.)](https://stackoverflow.com/a/6018043/3962267) I think it might be confusing, when both the email and Discord server blurbs are displayed, which text the middle paragraph here belongs to:

image

I think it might be more clear if the `emailBlurb.header` string came into play. But for the aforementioned reasons, I am not going to worry about it anyway unless the email mailing list signup form seems poised to make a comeback. I think this version of the site would be fine to be made public.

**Comment by toBeOfUse** [comment]
One thing that could be fixed is that on certain screen sizes, including my phone's, the social icons on the bottom of the home page overflow, putting the Discord icon on its own line:

image

I could fix this by setting the width of all these icons to 100%, causing them to try to be wide as possible, and then squeezing them in a flexbox row with a constrained width. In fact, I just did this on [the version of this branch on my fork](https://github.com/toBeOfUse/hacksu-2021/tree/tobeofuse-pr), after several minutes of struggling to create a version of this branch on my fork, but I'm not sure if I can add to this pull request or not - I haven't worked on a fork with multiple branches in a while.

**Comment by cseitz** [comment]
> I'm going to be honest: I'm kind of ["you ain't gonna need it"](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) when it comes to things like the ability to bring back the email signup form, which may never need to be done; I usually delete old code that I don't need in a project, secure in the knowledge that it'll be available in the git history as long as the project lives. [(Every file ever deleted from a repository can be displayed with a single git command.)](https://stackoverflow.com/a/6018043/3962267) I think it might be confusing, when both the email and Discord server blurbs are displayed, which text the middle paragraph here belongs to:
> 
> I think it might be more clear if the `emailBlurb.header` string came into play. But for the aforementioned reasons, I am not going to worry about it anyway unless the email mailing list signup form seems poised to make a comeback. I think this version of the site would be fine to be made public.

We will not be eliminating functionality like that unless we have a drop-in replacement. Stuff in HacKSU needs to be capable of being passed on through the years and we cannot expect future leaders to memorize that "oh hey, if you roll back our github enough, you will find our mailing list code". Our mailing list still works, we just don't use it. The only thing stopping us from restarting our use of it is putting in the effort to log in and send emails.

It is zero effort to put in a toggle (which we did), and given the size of our codebase; it is by no means a detriment to store code that is no longer being used that is on standby for it to be turned back on. For example, in KHE we disabled many questions on the hacker registration form because many applied to in-person meanwhile the event switched to virtual for COVID-19. This past year, all I had to do was re-enable those same functions as we needed them once we moved back in person. That is a prime example of why we shouldn't erase functionality unless it is completely broken and certain to never be used again.

As always, this is on a case-by-case basis; but we will not be eliminating our mailing list code given it still works and the potential for us to use it again. Future leaders may prefer emails instead of discord. If discord somehow got bought-out and taken offline or was no longer suitable for the club, we would need a good reliable alternative. The mailing list may be somewhat archaic, but it is very reliable and simple to maintain given Sendgrid handles everything for us beyond simply writing the email and clicking send.

**Comment by cseitz** [comment]
> One thing that could be fixed is that on certain screen sizes, including my phone's, the social icons on the bottom of the home page overflow, putting the Discord icon on its own line:
> 
> image
> 
> I could fix this by setting the width of all these icons to 100%, causing them to try to be wide as possible, and then squeezing them in a flexbox row with a constrained width. In fact, I just did this on [the version of this branch on my fork](https://github.com/toBeOfUse/hacksu-2021/tree/tobeofuse-pr), after several minutes of struggling to create a version of this branch on my fork, but I'm not sure if I can add to this pull request or not - I haven't worked on a fork with multiple branches in a while.

You can just work on this branch. Ignore the fork, that was just because you didn't yet have permission to work on hacksu repositories. Just git checkout this branch. Do not make any changes to main/master.

In terms of the logos themselves; we can just use a [media query ](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#targeting_media_features) to make the icons smaller on mobile screen sizes. I'll show you.

**Comment by cseitz** [comment]
@toBeOfUse Commit e8a0be2
```scss
@media (max-width: 800px) {
  .footer {
    .social img {
      height: 10vw;
      /* added this to show when the media query starts; makes the images red */
      filter: brightness(50%) sepia(100) saturate(100) hue-rotate(25deg);
    }
  }
}
```
chrome_bJZGNtWWTT

**Pull request merged**
