### PR TITLE
Update meeting location; minor text edits

### PR DESCRIPTION
**Pull request by toBeOfUse**
- Updates the meeting location to Bowman Hall, Room 218, and changes the picture to match
 - Replace "Some Text" description on Alumni page
 - Standardize capitalization of "HacKSU" in some places
 - Add prominent Discord server banner to "Get Involved" section

### CODE REVIEW

**Comment by toBeOfUse** [comment]
I notice on the live site that trying to sign up for the mailing list currently produces an error; I could try to debug that section of code and fix it in another PR, I'd just need a sendgrid API key to get to the point where the program currently crashes. I think that the Discord's announcements channel probably functions as a substitute for the mailing list at the moment

**Comment by cseitz** [comment]
> I notice on the live site that trying to sign up for the mailing list currently produces an error; I could try to debug that section of code and fix it in another PR, I'd just need a sendgrid API key to get to the point where the program currently crashes. I think that the Discord's announcements channel probably functions as a substitute for the mailing list at the moment !

I investigated this and it turns out that the API key was out of date. I put a new API key in and everything works as-is, no debugging or updates needed.

When I made the signup button, we heavily used the mailing list for updates. Since then, Discord is definitely the main way we send information out. Perhaps we'll decommission the mailing list?

**Comment by toBeOfUse** [comment]
The Discord server seems like such a natural hub for student organizations that it's weird for me to remember that they relied on mailing lists not that long ago. I think that the mailing list data and account could potentially be used to reach alumni in the future - I saw in the Discord server that Katie was pinging alumni to ask if they wanted to be mentors for the Hackathon, and I don't know whether they used it this year, but the mailing list seems like it could contain people who have graduated from HacKSU who maybe aren't reachable in the Discord server that should be contacted for stuff like that.

But it seems like it would make sense to have new attendees join the Discord server instead of signing up for the mailing list going forward. Do y'all (@cseitz? @Joshua2000B?) want me to remove the signup form for the mailing list from the home page? Otherwise, you said this looked ready to merge.

**Comment by cseitz** [comment]
We can just hide it for now. Don't erase the code, just comment it out.

**Comment by cseitz** [comment]
Better yet, turn it into a variable on the component that conditionally hides the email form.

**Comment by toBeOfUse** [comment]
@cseitz Done. There is now a variable in details.js that controls whether the email signup form is displayed, just like the existing variable that controls whether to display the virtual meeting location. There is also some more text in there just because I thought the invite banner on its own made for a barren-looking "Get Involved" section.

The "Get Involved" section with `showEmailSignup: false` (the current default):
image
With `showEmailSignup: true`:
image

**Comment by toBeOfUse** [comment]
Sorry, a couple little CSS things were bothering me, I'm done now

**Comment by cseitz** [comment]
https://github.com/hacksu/hacksu-2021/pull/24

**Pull request merged**
